baseURL: "/"
languageCode: en-gb
title: Luís Tavares
theme: PaperMod

paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Posts
      url: posts/
      weight: 1
    #    - name: Tags
    #      url: tags/
    #      weight: 3
    - name: Resumé
      url: /documents/cv.pdf
      weight: 4

params:
  homeInfoParams:
    imageUrl: "profile_picture.jpg"
    Title: "About me"
    Content: >
      - I am a software engineer keen on good and maintainable software development and problem-solving. Eager learner, always with an eye on new technologies.

      - 

      - Working as a Software Engineer @ [SingleStore](https://www.singlestore.com/). 

      -

      - You can get in touch with me or view my resumé through the links below.

  # Social links
  socialIcons:
    - name: github
      url: "https://github.com/luist18"
    - name: linkedin
      url: "https://www.linkedin.com/in/luis-tavares18/"
    - name: email
      url: "mailto:luistavares10@outlook.pt"
    - name: cv
      url: /documents/cv.pdf

  sectionPagesMenu: main

  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  UseHugoToc: true
  SearchHidden: true
  PostAuthorMeta: true
  ShowWordCount: false

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
